name: terraform-ci

on:
  pull_request:
    branches: [ "main" ]

jobs:
  fmt-validate-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform FMT (enforce style)
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan (save binary)
        run: terraform plan -no-color -out=tfplan.bin

      - name: Terraform Show â†’ plan.txt (full)
        run: terraform show -no-color tfplan.bin | tee plan.txt

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan-2399
          path: plan.txt
